Generalise draft format
SiegeEngineers/aoe2cm2 pull request #81
Opened 2021-05-13 22:13 UTC by HSZemi

Use more general terms (Civilisation → DraftOption) and modify the format for Presets and PlayerActions so they are no longer exclusively designed for Civilisation drafting.

This should make it easier to introduce new Draft types in the future, like map drafts.

2021-05-14 08:55 UTC, lalitpatel requested changes
I have taken a pass at it and suggested some changes.

We would probably need to abstract `DraftOptionGrid`, `PresetOptionCheckbox` and `DraftOptionPanel` since each Draft type may have a different UI. You plan to do it in this PR or this is for later? 

I will take another closer look tomorrow.

2021-05-14 08:55 UTC, lalitpatel commented on src/models/DraftsStore.ts
> +                                const message = new PlayerEvent(expectedAction.player, actionTypeFromAction(expectedAction.action), Civilisation.RANDOM.id, false, expectedAction.executingPlayer);
Should this be `Draftaction.RANDOM.id`?

2021-05-14 08:55 UTC, lalitpatel commented on src/models/Civilisation.ts
>      RANDOM = "RANDOM"
Can be removed.

2021-05-14 23:01 UTC, HSZemi commented on src/components/PresetEditor/PresetOptionCheckbox.tsx
> +        &nbsp;{t('civs.' + value.name)}
I guess realistically, we cannot do that in a general way. Think of a map draft. We can define translations for "Arabia" etc, but everything else we'll just have to use literally.

2021-05-15 13:22 UTC, HSZemi commented
> We would probably need to abstract `DraftOptionGrid`, `PresetOptionCheckbox` and `DraftOptionPanel` since each Draft type may have a different UI. You plan to do it in this PR or this is for later?

This pull request is supposed to only change things under the hood, but not modify anything yet that is visible to users of the site.

2021-05-17 12:51 UTC, lalitpatel approved these changes
LGTM 👍🏼

2021-05-17 21:38 UTC, merged